### ISSUE TITLE
Kibana Service Error

### ISSUE THREAD

**Issue by imewish** [realityforge/chef-kibana#78]
HI Im using this cookbook with test kitchen, on the kitchen converge im getting the following error,

![screen shot 2016-08-02 at 1 06 23 pm](https://cloud.githubusercontent.com/assets/11400953/17320636/338bdeba-58b2-11e6-94a4-f645dad10819.png)

On the second run of kitchen converge i couldn't reproduce it. converge finished successfully. But i couldnt see the kibana service running. 

Helps would be appreciated.

**Comment by cyberflow** [comment]
Hello @imewish, what platform you used?

**Comment by imewish** [comment]
@cyberflow Ubuntu 16.04

**Comment by imewish** [comment]
@cyberflow Could you reproduce the above issue?

**Comment by cyberflow** [comment]
@imewish yes i can. It's because Ubuntu 16.04 use systemd instead upstart. This cookbook not support systemd yet. I try to fix it as soon as possible.

**Comment by drenalin23** [comment]
@cyberflow I am close to submitting a PR to add support for this.  Hoping to have it done today.

**Comment by drenalin23** [comment]
@imewish and @cyberflow can you check the PR I submitted and see if things are working for you.  It is a WIP - there are a couple of tests failing in Travis for the new platforms (possibly related to netstat and apache2 scripts).

**Comment by cyberflow** [comment]
@drenalin23 I checked your PR on Ubuntu-16.04 with nginx and it's working OK.

**Comment by imewish** [comment]
@cyberflow have you merged the above update with master?

**Comment by drenalin23** [comment]
@imewish I will merge today after one more changed based on comments from @gfediere.  Pushed and testing now.

**Comment by drenalin23** [comment]
@imewish https://github.com/realityforge/chef-kibana/pull/80 was merged into master today.  Can you test on your end?

**Comment by imewish** [comment]
@drenalin23 Thanks. Will test today.

**Comment by imewish** [comment]
@drenalin23 I have tried it with kitchen ec2(attaching my .kitchen.yml file). the installation completed successfully and the kibana service is running fine. But when i try to access the kibana UI through my instance IP (http://instance_ip:5601/) i cant see the web GUI, it says site cant be reached. any idea why?

```
---
driver:
  name: ec2
  aws_ssh_key_id: sysadmin
  region: ap-south-1
  instance_type: t2.micro  
  security_group_ids: ["sg-xxxx"]
  subnet_id: subnet-xxxxxx
  require_chef_omnibus: true

transport:
  ssh_key: ~/.ssh/sysadmin.pem
  name: sftp
  

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    #image_id: ami-fbe83c98
    tags:
      Name: chefv3-kibana

suites:
- name: kibana4_nginx
  run_list:
    - 'recipe[netstat]'
    - 'recipe[kibana]'
    - 'recipe[nginx]'
    - 'recipe[kibana::nginx]'
    - 'recipe[java]'
    - 'recipe[elasticsearch]'
  attributes:
    kibana:
      version: '4'
      interface: '0.0.0.0'
      nginx:
        listen_http: 8080
    java:
      jdk_version: '8'

```
